server:
  port: 8082

spring:
#application name
  application:
    name: 02-product-service
  main:
    banner-mode: console

#oracle configuration
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: system
    password: manager
    driver-class-name: oracle.jdbc.OracleDriver

#jpa configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        format_sql: true
  defer-datasource-initialization: true

  
#query executed and data will insert at the time of server startup
  sql:
    init:
      mode: always

# apna application package
#com.vikas: INFO

#logging:
 # level:
 #   root: info       # sab band
 #   org.springframework: off
  #  org.hibernate: off
   # org.apache.tomcat: off

