INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'iPhone 15', 'Apple smartphone', 'MOBILE',
 79999, 50, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'Samsung S24', 'Samsung flagship phone', 'MOBILE',
 69999, 40, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'MacBook Air M2', 'Apple laptop', 'LAPTOP',
 114999, 20, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'Dell XPS 13', 'Premium Windows laptop', 'LAPTOP',
 104999, 15, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'Sony Headphones', 'Noise cancelling headphones', 'ACCESSORY',
 19999, 60, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'Apple Watch', 'Smart watch', 'WEARABLE',
 39999, 35, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'iPad Pro', 'Apple tablet', 'TABLET',
 89999, 25, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'Logitech Mouse', 'Wireless mouse', 'ACCESSORY',
 2999, 150, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'Mechanical Keyboard', 'Gaming keyboard', 'ACCESSORY',
 6999, 80, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO PRODUCTS
(PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, PRICE, STOCK,
 PRODUCT_ACTIVE, CREATED_BY, CREATED_DATE)
VALUES
(PRODUCT_SEQ.NEXTVAL, 'AirPods Pro', 'Wireless earbuds', 'ACCESSORY',
 24999, 45, 1, 'SYSTEM', SYSTIMESTAMP);
